<?php

namespace app\models;

use app\tools\HcUploadFile;
use Yii;

/**
 * This is the model class for table "staff".
 *
 * @property int $id 人员id、主键自增
 * @property string $Name 人员姓名
 * @property string $Title 职称
 * @property string $Status 状态
 * @property string $Email 邮箱
 * @property string $Image 照片
 * @property string $Profile 个人简介
 * @property string $other 其他
 *
 * @property Honor[] $honors
 * @property Paper[] $papers
 * @property StaffProject[] $projects
 */
class Staff extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'staff';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['Profile'], 'string'],
            [['Name', 'Title', 'Status', 'Email', 'Image', 'other'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'Name' => 'Name',
            'Title' => 'Title',
            'Status' => 'Status',
            'Email' => 'Email',
            'Image' => 'Image',
            'Profile' => 'Profile',
            'other' => 'Other',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHonors()
    {
        return $this->hasMany(Honor::className(), ['staff_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPapers()
    {
        return $this->hasMany(Paper::className(), ['staff_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjects()
    {
        return $this->hasMany(StaffProject::className(), ['staff_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $uploadFile = HcUploadFile::uploadFiles("Staff[Image]");
        if($uploadFile != null){
            $this->Image = $uploadFile['url'].$uploadFile['new_name'];
            echo $this->Image;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
